# Generated by Django 5.1.6 on 2025-03-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('air_date', models.DateField()),
                ('episode_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='episodes',
            field=models.ManyToManyField(to='api.episode'),
        ),
    ]
